name: Build Docker Image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make mvn execute
        run: chmod +x mvnw

      - name: Build Jar
        run: ./mvnw clean package

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build and tag image
        run: docker build -t ${{ secrets.DOCKER_USERNAME}}/user-app:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user-app:latest


