name: Build Docker Image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give execute permission to mvnw
        run: chmod +x mvnw

      - name: build Jar
        run: ./mvnw clean package

      - name: Build Docker Image
        run: docker build -t user-app .


